"""Add missing columns to assets table

Revision ID: 50fc85475775
Revises: df5ac68adbbe
Create Date: 2025-05-29 20:01:18.256602+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50fc85475775'
down_revision: Union[str, None] = 'df5ac68adbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('description', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('current_value', sa.Float(), nullable=True))
    op.alter_column('assets', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'RETIRED', 'DISPOSED', name='assetstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('assets_qr_code_key', 'assets', type_='unique')
    op.drop_index('ix_assets_category', table_name='assets')
    op.drop_index('ix_assets_name', table_name='assets')
    op.drop_column('assets', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('qr_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_assets_name', 'assets', ['name'], unique=False)
    op.create_index('ix_assets_category', 'assets', ['category'], unique=False)
    op.create_unique_constraint('assets_qr_code_key', 'assets', ['qr_code'])
    op.alter_column('assets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('assets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('assets', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'RETIRED', 'DISPOSED', name='assetstatus'),
               existing_nullable=False)
    op.alter_column('assets', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assets', 'current_value')
    op.drop_column('assets', 'description')
    # ### end Alembic commands ###
